### PR TITLE
Changes phyloref imports to use versionIRI

### PR DESCRIPTION
**Pull request by hlapp**
This is to isolate the examples from the pending (and future) new version(s) of the Phyloref Ontology that might be incompatible with how it is being used here.

### CODE REVIEW

**Comment by hlapp** [comment]
@gaurav you may want to do this too in generating the clade ontology if you want to isolate yourself from the upcoming changes for cases where you need to adapt the code.

**Comment by gaurav** [comment]
Done! I've also created issues to replace the Phyloref Ontology URI we've been using with a version IRI, so our code won't break every time the Phyloref Ontology is updated (phyloref/curation-tool#124, phyloref/clade-ontology#53, phyloref/jphyloref#42).

**Comment by hlapp** [comment]
@gaurav just keep in mind that you only change the _ontology IRI_ you import. Don't change the namespace declaration.

If this is confusing, note that it's the same as when you resolve a non-resolving import IRI to a local file on disk. Doing so doesn't somehow change the namespace to the local file on disk.

Another way of saying this is that a term from two different versions of the ontology isn't two entirely different terms. They would be though if they had different IRIs.

**Comment by gaurav** [comment]
@hlapp Yup, I know! I screwed up on `phyx.json` because I got confused between the imports (which should be the version IRI) and the prefix (which should be the base IRI). I just double-checked my change to phyx2ontology and didn't mess it up there, so I can confirm that I'm only an idiot *some* of the time.

**Comment by hlapp** [comment]
Ah, no worries. I find myself an idiot many times. You're in good company.

**Comment by ncellinese** [comment]
I fit the group perfectly!! 😆

**Pull request merged**
