### PR TITLE
Fixes and improvements for Maximum / Minimum Clade subclasses of Phyloreference

### LINKED ISSUE #34: Current release has minimum and maximum clade definition descriptions mixed up

### PR DESCRIPTION
**Pull request by hlapp**
Fixes #34, confusion of minimum and maximum clade definitions. Also adds logical definitions for these Phyloreference subclasses.

### CODE REVIEW

**Comment by hlapp** [comment]
Any comments @gaurav ?

**Comment by hlapp** [comment]
Actually this is problematic in the current model because for a minimum clade definition the phyloreference nod has neither _includes_TU_ nor _excludes_TU_ property restrictions; instead, it has a _has_Child_ restriction.

So I suspect this is not useful for **PhyloreferenceUsingMinimumCladeDefinition**.

**Comment by hlapp** [comment]
Maybe it's actually OK with the new proposed model. I'll leave it in for now.

**Comment by gaurav** [comment]
Will the use of `ObjectComplementOf` in the definition of PhyloreferenceUsingMinimumClade take us out of [OWL 2 EL](https://www.w3.org/TR/owl2-profiles/#Feature_Overview)? Apart from that, this looks good to me!

**Comment by hlapp** [comment]
It does, but if the axiom doesn't matter for our primary reasoning goals, that need not be a show stopper, because most EL reasoners will simply ignore axioms not in EL.

I should add that the axiom also isn't really appropriate anymore, so I'll be changing that to _has_Child some (excludes_TU some TU and includes_TU some TU)_.

**Pull request merged**
