### PR TITLE
Replaced single-element property chain with subproperty axiom

### LINKED ISSUE #4: Possible error in a propertyChainAxiom in excludes_lineage_to
Recent versions of JFact (I've tested 4.x and 5.x) cannot reason over the Phyloreferencing ontology. I reported this to JFact last October, and was told that the reasoning error was because of a property chain axiom in `excludes_lineage_to` that is invalid (https://github.com/owlcs/jfact/issues/19#issuecomment-336639215).

This isn't holding up development for now, since the ontology reasons fine in JFact 1.2.4, but fixing this might help us speed up reasoning with more advanced reasoners.

### PR DESCRIPTION
**Pull request by gaurav**
This closes #4, and allows [JFact 5](https://github.com/owlcs/jfact) to reason over this ontology when resolving phyloreferences. I used Protege 4.3 to create this file, so the OWL API version has increased from 3.3.1957 to 3.4.2.

Note that this change explicitly asserts that [obo:CDAO_0000174 (has_Descendant)](http://purl.obolibrary.org/obo/CDAO_0000174) and [obo:CDAO_0000149 (has_Child)](http://purl.obolibrary.org/obo/CDAO_0000149) are object properties. I'm not sure if this is necessary, but I don't think it does any harm.

### CODE REVIEW

**Comment by balhoff** [comment]
@gaurav just a tangential suggestion—for storage in version control I much prefer OWL Functional syntax over RDF/XML. OWL API outputs it one axiom per line.

**Comment by gaurav** [comment]
@balhoff Thanks for the suggestion! I've been using Functional Syntax for some debugging recently and I can see why you'd prefer it to RDF/XML!

**Comment by hlapp** [comment]
@gaurav it seems the diff is useless here. In part this is because there are two changes intermingled - one is going from OWL API 3.x to 4.x generating the output, and the other is the one you are proposing. Perhaps a first step would be to separate out the migration from OWL API 3.x to 4.x. It seems some configuration is also missing, such as using a prefix for the phyloref ontology. 

Depending on the result of making the change while not also changing the OWL API version, maybe we need to consider re-manufacturng the PR, using, for example, OWL functional syntax.

**Review by hlapp — CHANGES_REQUESTED** [review]
@gaurav it seems the diff is useless here. In part this is because there are two changes intermingled - one is going from OWL API 3.x to 4.x generating the output, and the other is the one you are proposing. Perhaps a first step would be to separate out the migration from OWL API 3.x to 4.x. It seems some configuration is also missing, such as using a prefix for the phyloref ontology. 

Depending on the result of making the change while not also changing the OWL API version, maybe we need to consider re-manufacturng the PR, using, for example, OWL functional syntax.

**Comment by gaurav** [comment]
@hlapp I got Protege 4.3 installed on my computer and made the change there, which resulted in a much more readable diff since it keeps us in OWLAPI 3.x! Let me know what you think.

Protege 4.3 has odd issues with reading the CDAO ontology, so I'd like to move this phylogeny to Protege 5 (and OWLAPI 4.x). I've created a PR for that at #20.

**Comment by hlapp** [comment]
> Note that this change explicitly asserts that obo:CDAO_0000174 (has_Descendant) and obo:CDAO_0000149 (has_Child) are object properties. I'm not sure if this is necessary, but I don't think it does any harm.

Not sure where the potential problem is here that you saw. Both properties are already asserted as object properties in CDAO, so this isn't redefining anything or even only adding an axiom that hadn't been there.

**Review by hlapp — APPROVED** [review]
Looks good. The essential change is to change the single element property chain to a subproperty axiom.

**Pull request merged**
