### PR TITLE
Translated ontology in RDF/XML with an OWL Functional Syntax

### PR DESCRIPTION
**Pull request by gaurav**
This PR translates phyloref.owl into OWL Functional Syntax as phyloref.ofn. To prevent duplication, it also deletes the old phyloref.owl -- phyloref.ofn will become the definitive ontology, and consumers can recreate the RDF/XML file as needed.

### CODE REVIEW

**Review by hlapp — APPROVED** [review]
Two comments:

1. It looks like changing to this format will lose the footer about which OWL API version generated it. This was useful provenance information. Perhaps we need to think about recording this separately?
2. We definitely do still need the OWL file, if only for tools that require RDF/XML format for imports etc. So if we are switching to `.ofn` as the master file, then maybe we need to define a release process that generated the RDF/XML file.

Either consideration exceeds, I think, the scope of this PR (given that this is all pre-alpha, otherwise item 2 would not), so I'll give this approval status anyway. But we need to track these issues, so at the very least create tracker items.

**Comment by gaurav** [comment]
I think those are both good reasons not to merge right away, and there isn't an urgent need to do so until we start adding terms to the Phyloref Ontology in earnest. Maybe we should close this PR for now and revisit it at that time?

**Comment by hlapp** [comment]
I think what you're trying to suggest is the following:
1. Let's turn this from a PR into an issue because although there are good reasons to assume we'll come back to this in the not too distant future, we'll have to redo it then, because it's a conversion.
2. Even in RDF/XML changes will still be relatively easy to identify and evaluate so long as the OWL API version does not also change dramatically between old and new. I.e., so long as we take to separate OWL API upgrades from actual changes to the ontology, we should be OK, at least for some time?
3. Although ultimately we will want an automated release process, you think implementing it now is premature.

I don't necessarily feel the same way about (3) but am willing to buy into (1) and (2), so if this captures your argument, feel free to take the corresponding action (file issue, close this PR, convert ontology to latest OWL API).

**Comment by gaurav** [comment]
Yup, that's what I meant! Closing this PR now; we can continue the discussion in #24 and re-open it when we're ready to build a proper release workflow.

**Pull request closed without merging**
